version: "3.8"
services:
  corrector:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      JWT_SECRET: dasldjh4h1jk4kadhasdsa
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_BUCKET: uomlms
      KAFKA_URL: "kafka:9092"
      KAFKA_GROUP_ID: "corrector-group"
      ROBERTS_LIB: /app/lib/roberts
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: 
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper